from manimlib import VMobject
from manimlib.utils.color import color_to_rgb
import math

def color_to_hex(color):
    rgb = color_to_rgb(color)
    return "#%02x%02x%02x" % (int(rgb[0] * 255), int(rgb[1] * 255), int(rgb[2] * 255))

def vmobject_to_svg_path(vmobject, scene, width, height):
    try:
        points = vmobject.get_points()
    except AttributeError:
        return ""
        
    if len(points) == 0:
        return ""

    camera = scene.camera
    frame = camera.frame
    
    # Focal distance in canonical units
    d = frame.get_focal_distance() / frame.get_scale()
    
    def transform(p):
        p_local = frame.to_fixed_frame_point(p)
        z = p_local[2]
        if math.isclose(z, d):
            factor = 1000.0
        else:
            factor = d / (d - z)
            
        x_proj = p_local[0] * factor
        y_proj = p_local[1] * factor
        
        # Fixed frame height is 8.0 units (standard Manim)
        x_pixel = x_proj * (height / 8.0) + width / 2
        y_pixel = -y_proj * (height / 8.0) + height / 2
        
        return x_pixel, y_pixel

    path_data = []
    # ManimGL uses quadratic beziers.
    # Points are stored as: [anch1, ctrl1, anch2, ctrl2, anch3, ...]
    
    if len(points) > 0:
        start = transform(points[0])
        path_data.append(f"M {start[0]:.3f} {start[1]:.3f}")
        
        # Each segment is 2 points: control and end-anchor.
        for i in range(1, len(points), 2):
            if i + 1 >= len(points):
                break
            control = transform(points[i])
            end = transform(points[i+1])
            path_data.append(f"Q {control[0]:.3f} {control[1]:.3f}, {end[0]:.3f} {end[1]:.3f}")

    if not path_data:
        return ""

    try:
        fill_color = color_to_hex(vmobject.get_fill_color())
        fill_opacity = vmobject.get_fill_opacity()
        stroke_color = color_to_hex(vmobject.get_stroke_color())
        stroke_opacity = vmobject.get_stroke_opacity()
        stroke_width = vmobject.get_stroke_width()
    except Exception:
        return ""
    
    path_str = " ".join(path_data)
    style = f'fill="{fill_color}" fill-opacity="{fill_opacity}" stroke="{stroke_color}" stroke-opacity="{stroke_opacity}" stroke-width="{stroke_width}"'
    return f'<path d="{path_str}" {style} />'

def save_scene_to_svg(scene, file_path):
    camera = scene.camera
    width = camera.get_pixel_width()
    height = camera.get_pixel_height()
    
    svg_header = [
        f'<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
        f'<!-- Generated by ManimGL SVG Exporter (Quadratic Bezier Fix) -->',
        f'<svg width="{width}" height="{height}" viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" style="background-color: black;">'
    ]
    svg_body = []
    
    for mob in scene.mobjects:
        for submob in mob.get_family():
            if isinstance(submob, VMobject):
                path = vmobject_to_svg_path(submob, scene, width, height)
                if path:
                    svg_body.append(path)
                    
    svg_footer = ['</svg>']
    
    content = "\n".join(svg_header + svg_body + svg_footer)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"SVG saved to {file_path}")
